
export const FORMULARIO_TAREA = 'FORMULARIO_TAREA';
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PASAR_VALIDACION_TAREA = 'PASAR_VALIDACION_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const TAREA_ERROR = 'TAREA_ERROR';

export const ACTIVIDADES_TAREA = 'ACTIVIDADES_TAREA';
export const AGREGAR_ACTIVIDAD = 'AGREGAR_ACTIVIDAD';
export const VALIDAR_ACTIVIDAD = 'VALIDAR_ACTIVIDAD';
export const PASAR_VALIDACION_ACTIVIDAD = 'PASAR_VALIDACION_ACTIVIDAD';
export const ELIMINAR_ACTIVIDAD = 'ELIMINAR_ACTIVIDAD';
export const ACTIVIDAD_ACTUAL = 'ACTIVIDAD_ACTUAL';
export const EDITAR_ACTIVIDAD = 'EDITAR_ACTIVIDAD';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const SESION_EXITOSA = 'SESION_EXITOSA';
export const SESION_ERROR = 'SESION_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';